GERMAN_BOOKING_DATE_COLUMN = "Buchungstag"
BOOKING_DATE_COLUMN = "Booking Date"
PARTNER_NAME_COLUMN = "Partner Name"
AMOUNT_EUR_COLUMN = "Amount (EUR)"
CSV_FILENAME_COLUMN = "csvfilename"
CATEGORY_COLUMN = "CATEGORY"
TOTAL_AMOUNT_EUR_COLUMN = "Total Amount (EUR)"
CSV_FILE_NAME_COLUMN = "CSV File Name"
OCCURRENCES_COLUMN = "Occurrences"

GERMAN_COLUMN_RENAMES = {
    GERMAN_BOOKING_DATE_COLUMN: BOOKING_DATE_COLUMN,
    "Buchungstext": PARTNER_NAME_COLUMN,
    "Betrag": AMOUNT_EUR_COLUMN,
}

REQUIRED_SOURCE_COLUMNS = [
    BOOKING_DATE_COLUMN,
    PARTNER_NAME_COLUMN,
    AMOUNT_EUR_COLUMN,
]
DEFAULT_COLUMNS_TO_KEEP = REQUIRED_SOURCE_COLUMNS + [CSV_FILENAME_COLUMN]
REQUIRED_SUMMARY_COLUMNS = [AMOUNT_EUR_COLUMN, CATEGORY_COLUMN]